using System;
using System.Collections.Generic;
using System.Text;
using DevExpress.XtraCharts.Localization;

namespace DevExpress.Localization.Zh_Chs
{
    public class ChartLocalizer_zhchs : ChartLocalizer
    {
        public override string Language
        { get { return "简体中文"; } }
        public override string GetLocalizedString(ChartStringId id)
        {
            switch (id)
            {
                case ChartStringId.DefaultMinValue: return "最小";
                case ChartStringId.DefaultMaxValue: return "最大";
                case ChartStringId.MsgMinMaxDifferentTypes: return "最大值和最小值的类型不匹配。";
                case ChartStringId.MsgIncorrectAxisRange: return "轴范围({0})的最小值应该小于它的最大值({1})。";
                case ChartStringId.SeriesPrefix: return "系列";
                case ChartStringId.PalettePrefix: return "调色板";
                case ChartStringId.ArgumentMember: return "参数";
                case ChartStringId.ValueMember: return "值";
                case ChartStringId.LowValueMember: return "低";
                case ChartStringId.HighValueMember: return "高";
                case ChartStringId.OpenValueMember: return "打开";
                case ChartStringId.CloseValueMember: return "关闭";
                case ChartStringId.AutocreatedSeriesName: return "自动创建系列";
                case ChartStringId.DefaultDataFilterName: return "数据过滤器";
                case ChartStringId.DefaultChartTitle: return "图表标题";
                case ChartStringId.DefaultSeriesPointFilterName: return "系列点过滤器";
                case ChartStringId.MsgEmptyArrayOfValues: return "此值数组为空。";
                case ChartStringId.MsgSeriesViewDoesNotExist: return "{0}系列视图不存在。";
                case ChartStringId.MsgEquallySpacedItemsNotUsable: return "在方向属性设置为{0}时，该属性不能使用。";
                case ChartStringId.MsgItemNotInCollection: return "采集中不包含该指定项目。";
                case ChartStringId.MsgIncorrectValue: return "值\"{0}\"不是参数\"{1}\"的正确值。";
                case ChartStringId.MsgIncompatiblePointType: return "\"{0}\"点的类型和{1}标度不兼容。";
                case ChartStringId.MsgIncompatibleArgumentDataMember: return "\"{0}\"参数数据成员的类型和{1}标度不兼容。";
                case ChartStringId.MsgIncompatibleValueDataMember: return "\"{0}\"值数据成员的类型和{1}标度不兼容。";
                case ChartStringId.MsgDesignTimeOnlySetting: return "程序运行时不能设置此项属性。";
                case ChartStringId.MsgInvalidDataSource: return "无效的数据源类型(没有支持的接口可执行)。";
                case ChartStringId.MsgIncorrectDataMember: return "数据源中不包含一个名为\"{0}\"的数据成员。";
                case ChartStringId.MsgInvalidSortingKey: return "不能将排序键的值设置为{0}。";
                case ChartStringId.MsgInvalidFilterCondition: return "{0}情况不能应用\"{1}\"数据。";
                case ChartStringId.MsgIncorrectDataAdapter: return "{0}对象不是一个数据适配器。";
                case ChartStringId.MsgModifyDefaultPaletteError: return "默认使用该调色板，且不能修改该调色板。";
                case ChartStringId.MsgAddExistingPaletteError: return "存储器中已经存在名称为{0}的调色板。";
                case ChartStringId.MsgInternalPropertyChangeError: return "这个属性只能供内部使用。不允许改变它的值。";
                case ChartStringId.MsgPaletteNotFound: return "图表在不包含名称为{0}的调色板。";
                case ChartStringId.MsgLabelSettingRuntimeError: return "在运行时不能设置\"标记\"属性。";
                case ChartStringId.MsgPointOptionsSettingRuntimeError: return "在运行时不能设置\"点选项\"属性。";
                case ChartStringId.MsgIncorrectNumericPrecision: return "精度应该大于等于0。";
                case ChartStringId.MsgIncorrectAxisThickness: return "轴的厚度应该大于0。";
                case ChartStringId.MsgIncorrectBarWidth: return "柱状条的宽度应该大于0。";
                case ChartStringId.MsgIncorrectBarDepth: return "柱状条的深度应该大于0。";
                case ChartStringId.MsgIncorrectLineWidth: return "线宽应该大于0。";
                case ChartStringId.MsgIncorrectAreaWidth: return "面积的宽度应该大于0。";
                case ChartStringId.MsgIncorrectBorderThickness: return "边沿宽度应该大于0。";
                case ChartStringId.MsgIncorrectChartTitleIndent: return "标题缩进应该大于等于0且小于1000。";
                case ChartStringId.MsgIncorrectLegendMarkerSize: return "图例记号的大小应该大于0且小于1000。";
                case ChartStringId.MsgIncorrectMarkerSize: return "标记大小应该大于１。";
                case ChartStringId.MsgIncorrectMarkerStarPointCount: return "星点的数量应该大于3且小于101。";
                case ChartStringId.MsgIncorrectPieSeriesLabelColumnIndent: return "列缩进应该大于等于0。";
                case ChartStringId.MsgIncorrectRangeBarSeriesLabelIndent: return "缩进量应该大于等于0。";
                case ChartStringId.MsgIncorrectPercentPrecision: return "百分数值的精度应该大于0。";
                case ChartStringId.MsgIncorrectSeriesLabelLineLength: return "线长应该大于等于0且小于1000。";
                case ChartStringId.MsgIncorrectStripConstructorParameters: return "标记线的最大极限和最小极限不能相同。";
                case ChartStringId.MsgIncorrectStripLimitAxisValue: return "StripLimit对象的轴值属性不能设置为空。";
                case ChartStringId.MsgIncorrectStripMinLimit: return "标记线的最小极限必须小于最大极限。";
                case ChartStringId.MsgIncorrectStripMaxLimit: return "标记线的最大极限必须大于最小极限。";
                case ChartStringId.MsgIncorrectLineThickness: return "线厚应该大于0。";
                case ChartStringId.MsgIncorrectShadowSize: return "阴影大小应该大于0。";
                case ChartStringId.MsgIncorrectTickmarkThickness: return "刻度的厚度应该大于0。";
                case ChartStringId.MsgIncorrectTickmarkLength: return "刻度的长度应该大于0。";
                case ChartStringId.MsgIncorrectMinorCount: return "最小计数的数量应该大于0且小于100。";
                case ChartStringId.MsgIncorrectTickmarkMinorThickness: return "最小刻度的厚度应该大于0。";
                case ChartStringId.MsgIncorrectTickmarkMinorLength: return "最小刻度的长度应该大于0。";
                case ChartStringId.MsgIncorrectPercentValue: return "百分数值应该大于等于0且小于等于100。";
                case ChartStringId.MsgIncorrectSimpleDiagramDimension: return "简单图表的尺度应该大于0且小于100。";
                case ChartStringId.MsgIncorrectStockLevelLineLengthValue: return "股指线的长度值应该大于等于0。";
                case ChartStringId.MsgIncorrectReductionColorValue: return "减少颜色值不能为空。";
                case ChartStringId.MsgIncorrectLabelAngle: return "标记的角度大小应该大于等于-360度且小于等于360度。";
                case ChartStringId.MsgIncorrectImageFormat: return "不可能按指定的图象格式输出表格。";
                case ChartStringId.MsgIncorrectImageBounds: return "不能创建指定大小的图象。";
               // case ChartStringId.MsgIncorrectUseImageProperty: return "图象属性不能用于网络图表控件，请使用ImageUrl属性替代。";
                case ChartStringId.MsgIncorrectUseImageUrlProperty: return "ImageUrl属性不能用于网络图表控件，请使用图象属性替代。";
                case ChartStringId.MsgIncorrectTaskLinkMinIndent: return "任务连接的最小缩进应该大于等于0。";
                case ChartStringId.MsgIncorrectArrowWidth: return "箭头的宽度应该总为大于0的奇数。";
                case ChartStringId.MsgIncorrectArrowHeight: return "箭头的高度应该大于0。";
                case ChartStringId.MsgEmptyArgument: return "参数不能为空。";
                case ChartStringId.MsgIncorrectValueDataMemberCount: return "需要为当前系列视图指定{0}值数据成员。";
                case ChartStringId.MsgPaletteDoubleClickToEdit: return "双击编辑...";
                case ChartStringId.MsgInvalidPaletteName: return "不能将带有空名称(\"\")的调色板增加到调色板存储器中。请为该调色板指定另外的名称。";
                case ChartStringId.MsgInvalidScaleType: return "按标度的内部表示方法转换的指定值与当前的标度类型不兼容。";
                case ChartStringId.MsgIncorrectTransformationMatrix: return "不正确的变换矩阵。";
                case ChartStringId.MsgIncorrectPerspectiveAngle: return "透视角应该大于等于0且小于180。";
                case ChartStringId.MsgIncorrectPieDepth: return "饼图的深度应该大于等于0且小于等于100，因为它的值是按百分数度量的。";
                case ChartStringId.MsgIncorrectSeriesDistance: return "系列的间距应该大于等于0。";
                case ChartStringId.MsgIncorrectSeriesDistanceFixed: return "固定系列的间距应该大于等于0。";
                case ChartStringId.MsgIncorrectSeriesIndentFixed: return "固定系列的缩进应该大于等于0。";
                case ChartStringId.MsgIncorrectPlaneDepthFixed: return "固定平面的深度应该大于等于1。";
                case ChartStringId.MsgIncorrectGridSpacing: return "删格间距应该大于0。";
                case ChartStringId.MsgIncompatibleArgumentScaleType: return "{0}参数的标度类型和{1}系列视图不兼容。";
                case ChartStringId.MsgIncompatibleValueScaleType: return "{0}值标度类型和{1}系列视图不兼容。";
                case ChartStringId.MsgIncorrectConstantLineAxisValue: return "实线对象的轴值不能设置为空。";
                case ChartStringId.MsgIncorrectCustomAxisLabelAxisValue: return "CustomAxisLabel对象，其轴值不能设置为空。";

                case ChartStringId.MsgInvalidZeroAxisAlignment: return "对于二级轴，对齐不能设置为对齐.Zero。";
                case ChartStringId.MsgNullSeriesViewAxisX: return "系列视图的X轴不能设置为空。";
                case ChartStringId.MsgNullSeriesViewAxisY: return "系列视图的Y轴不能设置为空。";
                case ChartStringId.MsgIncorrectParentSeriesPointOwner: return "父系列的所有者不能为空且必须为此系列类型。";
                case ChartStringId.MsgSeriesViewNotSupportRelations: return "系列视图不支持关系。";
                case ChartStringId.MsgIncorrectChildSeriesPointOwner: return "子系列点的所有者不能为空，且必须是此系列类型。";
                case ChartStringId.MsgIncorrectChildSeriesPointID: return "子系列点的ID必须为正或者等于0。";
                case ChartStringId.MsgSelfRelatedSeriesPoint: return "系列点不能和它自身有关联。";
                case ChartStringId.MsgSeriesPointRelationAlreadyExists: return "系列点的关系采集已经包含此关系。";
                case ChartStringId.MsgChildSeriesPointNotExist: return "ID等于{0}的子系列点不存在。";
                case ChartStringId.MsgRelationChildPointIDNotUnique: return "关系的ChildPointID必须是独有的。";
                case ChartStringId.MsgSeriesPointIDNotUnique: return "系列点的ID必须是独有的。";
                case ChartStringId.MsgIncorrectFont: return "字体不能为空";
                case ChartStringId.MsgIncorrectScrollBarThickness: return "滚动条的厚度应该大于等于3且小于等于25。";
                case ChartStringId.MsgIncorrectZoomPercent: return "缩放百分数应该大于0且小于等于{0}。";
                case ChartStringId.MsgIncorrectHorizontalScrollPercent: return "水平滚动百分比应该大于等于-{0}且小于等于{0}。";
                case ChartStringId.MsgIncorrectVerticalScrollPercent: return "垂直滚动百分数应该大于等于-{0}且小于等于{0}。";
                case ChartStringId.MsgUnregisterGroupError: return "这个组已经取消注册。";
                case ChartStringId.MsgUnregisterPageError: return "这个页已经取消注册。";
                case ChartStringId.MsgWizardAbsractPageType: return "{0}是抽象的，所以该类型的对象不能有实例且不能增加为导向页面。";
                case ChartStringId.MsgWizardIncorrectBasePageType: return "{0}必须从{1}类继承。";
                case ChartStringId.MsgWizardNonUniquePageType: return "类型{0}的页面已经注册。对于一个特定的类型只能有一个页面。";
                case ChartStringId.MsgWizardNonUniqueGroupName: return "名称为{0}的组已经注册。";
                case ChartStringId.MsgOrderArrayLengthMismatch: return "指令数组的长度和注册元素的总数量不相等。";
                case ChartStringId.MsgOrderUnregisteredElementFound: return "发现没有注册的元素。";
                case ChartStringId.MsgOrderRepeatedElementFound: return "同一元素在指令数组中已重复多次。";
                case ChartStringId.MsgAddPresentViewType: return "指定的视类型在采集中已经存在。";
                case ChartStringId.MsgAddLastViewType: return "在此采集中不能添加任何视类型，因为在向导中至少需要一个视类型是可用的。";
                case ChartStringId.MsgCalcHitInfoNotSupported: return "3维图表类型不支持点击测试。这种方法只用于2维图表类型。";
                case ChartStringId.MsgIncorrectAppearanceName: return "图表不包含名称为{0}的外观。";
                case ChartStringId.MsgNotChartControl: return "指定对象不是一个图表控件。";
                case ChartStringId.MsgNotBelongingChart: return "这个控件不包含指定图表。";
                case ChartStringId.MsgInitializeChartNotFound: return "没有发现图表控件，或者是这个控件上有几个图表。解决这个问题，你需要使用向导页。运行初始化页面并手动为控件指定图表。";
                case ChartStringId.MsgIncompatibleByViewType: return "视图类型";
                case ChartStringId.MsgIncompatibleByArgumentScaleType: return "参数标度类型";
                case ChartStringId.MsgIncompatibleByValueScaleType: return "值标度类型";
                case ChartStringId.MsgInvalidExplodedSeriesPoint: return "这些指定的系列点不属于当前饼系列视图的系列点采集，所以它们不能加到爆破分散点的采集当中。";
                case ChartStringId.MsgInvalidExplodedModeAdd: return "因为当前的饼系列视图显示了用系列模板创建的系列，所以指定的系列点不能加到爆破分散点的采集当中。你需要使用另外的爆破分散模式来替代。";
                case ChartStringId.MsgInvalidExplodedModeRemove: return "因为当前的饼系列视图显示了用系列模板创建的系列，所以指定的系列点不能从爆破分散点的采集当中移除。你需要使用另外的爆破分散模式来替代。";
                case ChartStringId.MsgIncorrectExplodedDistancePercentage: return "爆破分散的间距其百分数值应该大于0。";
                case ChartStringId.MsgIncorrectPaletteBaseColorNumber: return "调色板的基础色数量应该大于等于0且小于等于其总颜色数量。";
                case ChartStringId.MsgDenyChangeSeriesPointCollection: return "不能人为改变系列点的集合，因为图表和数据是绑定的。";
                case ChartStringId.MsgDenyChangeSeriesPointAgument: return "不能人为改变系列点的参数，因为图表和数据是绑定的。";
                case ChartStringId.MsgDenyChangeSeriesPointValue: return "不能人为改变系列点的值，因为图表和数据是绑定的。";
                case ChartStringId.MsgIncorrectStartAngle: return "起始角的值应该大于等于-360度且小于等于360度。";
                case ChartStringId.MsgPolarAxisXRangeChanged: return "极地X轴的范围不能改变。";
                case ChartStringId.MsgPolarAxisXGridSpacingChanged: return "极地X轴的栅格间隔不能改变。";
                case ChartStringId.MsgIncorrectPieArgumentScaleType: return "不能指定{0}参数的标度类型，因为当前的爆破分散点过滤器与它不匹配。";
                case ChartStringId.MsgIncorrectBarSeriesLabelIndent: return "缩进量应该大于等于0。";
                case ChartStringId.VerbAbout: return "关于";
                case ChartStringId.VerbPopulate: return "展示";
                case ChartStringId.VerbSeries: return "系列...";
                case ChartStringId.TrnSeriesChanged: return "改变系列";
                case ChartStringId.TrnDataFiltersChanged: return "改变数据过滤器";
                case ChartStringId.TrnChartTitlesChanged: return "改变图表标题";
                case ChartStringId.TrnStripsChanged: return "改变标记线";
                case ChartStringId.TrnPalettesChanged: return "改变调色板";
                case ChartStringId.TrnConstantLinesChanged: return "改变实线";
                case ChartStringId.TrnCustomAxisLabelChanged: return "改变定制的轴标记";
                case ChartStringId.TrnSecondaryAxesXChanged: return "改变二级X轴";
                case ChartStringId.TrnSecondaryAxesYChanged: return "改变二级Y轴";
                case ChartStringId.TrnChartWizard: return "应用图表向导设置";
                case ChartStringId.TrnSeriesDeleted: return "删除系列";
                case ChartStringId.TrnChartTitleDeleted: return "删除图表标题";
                case ChartStringId.TrnConstantLineDeleted: return "改变实线";
                case ChartStringId.TrnSecondryAxisXDeleted: return "删除二级X轴";
                case ChartStringId.TrnSecondryAxisYDeleted: return "删除二级Y轴";
                case ChartStringId.TrnExplodedPoints: return "改变爆破分散点";
                case ChartStringId.TrnExplodedPointsFilters: return "改变爆破分散点过滤器";
                case ChartStringId.FontFormat: return "{0}, {1}点, {2}";
                case ChartStringId.AxisXDefaultTitle: return "参数轴";
                case ChartStringId.AxisYDefaultTitle: return "数值轴";
                case ChartStringId.DefaultWizardPageLabel: return "向导页";
                case ChartStringId.MenuItemAdd: return "增加";
                case ChartStringId.MenuItemInsert: return "插入";
                case ChartStringId.MenuItemDelete: return "删除";
                case ChartStringId.MenuItemClear: return "清除";
                case ChartStringId.MenuItemMoveUp: return "上移";
                case ChartStringId.MenuItemMoveDown: return "下移";
                case ChartStringId.WizAutoCreatedSeries: return "自动创建系列";
                case ChartStringId.WizSpecifyDataFilters: return "点击省略符按钮...";
                case ChartStringId.WizDataFiltersEntered: return "{0} 数据过滤器(s)";
                case ChartStringId.WizDataFiltersDisabled: return "(空)";
                case ChartStringId.WizBackImageFileNameFilter: return "图象文件(*.gif;*.jpg;*.jpeg;*.bmp;*.wmf;*.png)|*.gif;*.jpg;*.jpeg;*.bmp;*.wmf;*.png|All files(*.*)|*.*";
                case ChartStringId.WizConstructionGroupName: return "构造";
                case ChartStringId.WizPresentationGroupName: return "效果";
                case ChartStringId.WizChartTypePageName: return "图表类型";
                case ChartStringId.WizAppearancePageName: return "外观";
                case ChartStringId.WizSeriesPageName: return "系列";
                case ChartStringId.WizDataPageName: return "数据";
                case ChartStringId.WizDiagramPageName: return "图表";
                case ChartStringId.WizAxesPageName: return "轴";
                case ChartStringId.WizSeriesViewPageName: return "系列视图";
                case ChartStringId.WizSeriesLabelsPageName: return "点标记";
                case ChartStringId.WizChartTitlesPageName: return "图表标题";
                case ChartStringId.WizLegendPageName: return "图例";
                case ChartStringId.WizChartTypePageDescription: return "选择您需要使用的图表类型。如果要按图表分组过滤图表类型，请选择下拉列表中的选项。";
                case ChartStringId.WizAppearancePageDescription: return "为颜色系列或者它们的数据点选择调色板。同时选择基于当前调色板的图表外观的指定风格。";
                case ChartStringId.WizDiagramPageDescription: return "定制图表属性。";
                case ChartStringId.WizLegendPageDescription: return "定制图例属性。";
                case ChartStringId.WizFormTitle: return "制表向导";
                case ChartStringId.WizHatchMin: return "最小";
                case ChartStringId.WizHatchMax: return "最大";
                case ChartStringId.WizValueLevelLow: return "低";
                case ChartStringId.WizValueLevelHigh: return "高";
                case ChartStringId.WizValueLevelOpen: return "打开";
                case ChartStringId.WizValueLevelClose: return "关闭";
                case ChartStringId.SvnSideBySideBar: return "柱状";
                case ChartStringId.WizErrorMessageTitle: return "制表向导";
                case ChartStringId.WizAnnotationConnectorStyleLine: return "线形";
                case ChartStringId.SvnStackedBar: return "柱状堆叠";
                case ChartStringId.SvnFullStackedBar: return "百分之百柱状堆叠";
                case ChartStringId.SvnPie: return "饼状";
                case ChartStringId.SvnPoint: return "点状";
                case ChartStringId.SvnLine: return "线形";
                case ChartStringId.SvnStepLine: return "阶越线形";
                case ChartStringId.SvnArea: return "面积";
                case ChartStringId.SvnStackedArea: return "面积堆叠";
                case ChartStringId.SvnFullStackedArea: return "百分之百面积堆叠";
                case ChartStringId.SvnArea3D: return "3维面积";
                case ChartStringId.SvnStackedArea3D: return "3维面积堆叠";
                case ChartStringId.SvnFullStackedArea3D: return "百分之百3维面积堆叠";
                case ChartStringId.SvnStock: return "股指";
                case ChartStringId.SvnCandleStick: return "蜡烛线";
                case ChartStringId.SvnSideBySideRangeBar: return "并排范围柱状";
                case ChartStringId.SvnOverlappedRangeBar: return "范围柱状";
                case ChartStringId.SvnSideBySideGantt: return "并排甘特";
                case ChartStringId.SvnOverlappedGantt: return "甘特";
                case ChartStringId.SvnManhattanBar: return "曼哈顿柱状";
                case ChartStringId.SvnPie3D: return "3维饼状";
                case ChartStringId.SvnLine3D: return "3维线形";
                case ChartStringId.SvnStepLine3D: return "3维阶越线形";
                case ChartStringId.SvnRadarPoint: return "雷达点状";
                case ChartStringId.SvnRadarLine: return "雷达线形";
                case ChartStringId.SvnRadarArea: return "雷达面积";
                case ChartStringId.SvnPolarPoint: return "极地点状";
                case ChartStringId.SvnPolarLine: return "极地线形";
                case ChartStringId.SvnPolarArea: return "极地面积";
                case ChartStringId.IncompatibleSeriesView: return "(不兼容)";
                case ChartStringId.InvisibleSeriesView: return "(不可见)";
                case ChartStringId.IncompatibleSeriesHeader: return "这个系列是不兼容的。";
                case ChartStringId.IncompatibleSeriesMessage: return "通过 {0} 和 \"{1}\"";
                case ChartStringId.IOCaption: return "非法操作";
                case ChartStringId.IODeleteAxis: return "主轴不能删除。如果需要隐藏它，可将其可见属性设置为假。";
                case ChartStringId.StyleAllColors: return "所有颜色";
                case ChartStringId.StyleColorNumber: return "颜色 {0}";
                case ChartStringId.FunctionArgumentName: return "参数";

            }
            return base.GetLocalizedString(id);
        }
    }
}
