using System;
using System.Collections.Generic;
using System.Text;
using DevExpress.XtraRichEdit.Localization;

namespace DevExpress.Localization.Zh_Chs
{
    public class XtraRichEditLocalizer_zhchs : XtraRichEditLocalizer
    {
        public override string Language
        { get { return "简体中文"; } }
        public override string GetLocalizedString(XtraRichEditStringId id)
        {
            switch (id)
            {
                case XtraRichEditStringId.DefaultStyleName_BodyText3: return "本文文字 3";
                case XtraRichEditStringId.MenuCmd_FontSubscript: return "下标";
                case XtraRichEditStringId.Caption_LineSpacingAtLeast: return "至少";
                case XtraRichEditStringId.DefaultStyleName_HTMLAcronym: return "HTML Acronym ";
                case XtraRichEditStringId.FieldMapTitle: return "尊称";
                case XtraRichEditStringId.DefaultStyleName_Salutation: return "问候语";
                case XtraRichEditStringId.DefaultStyleName_HTMLSample: return "HTML Sample ";
                case XtraRichEditStringId.MenuCmd_ToggleHiddenTextDescription: return "隐藏.";
                case XtraRichEditStringId.DefaultStyleName_ListBullet2: return "列表项目符号 2";
                case XtraRichEditStringId.DefaultStyleName_Table3Deffects2: return "表格 3D 效果 2";
                case XtraRichEditStringId.MenuCmd_DraftViewDescription: return "草案检视";
                case XtraRichEditStringId.MenuCmd_MoveLineUp: return "往上移一行";
                case XtraRichEditStringId.MenuCmd_CutSelectionDescription: return "将文件上所选择的内容剪下, 并放到系统剪贴簿中.";
                case XtraRichEditStringId.MenuCmd_EnsureCaretVisibleVertically: return "将插入号垂直显示";
                case XtraRichEditStringId.Msg_InvalidSetCharacterProperties: return "错误: 无法在未初起化或文件中没有对象的情形下设定字符属性";
                case XtraRichEditStringId.MenuCmd_ShiftTabKey: return "ShiftTab 键";
                case XtraRichEditStringId.DefaultStyleName_heading2: return "标题 2";
                case XtraRichEditStringId.MenuCmd_ToggleFieldCodesDescription: return "切换字段代码";
                case XtraRichEditStringId.Msg_UsedWrongUnit: return "使用错误的测量单位.";
                case XtraRichEditStringId.MenuCmd_ChangeCharacterStyleDescription: return "变更字符样式";
                case XtraRichEditStringId.DefaultStyleName_ListBullet: return "列表项目符号 ";
                case XtraRichEditStringId.MenuCmd_MoveNextWordDescription: return "移到下一个字符";
                case XtraRichEditStringId.Msg_InvalidValueRange: return "数值需介于 {0} 与 {1} 之间.";
                case XtraRichEditStringId.UnitAbbreviation_Millimeter: return " 公厘";
                case XtraRichEditStringId.MenuCmd_InsertEmDashDescription: return "插入长破折号";
                case XtraRichEditStringId.MenuCmd_MoveLineDown: return "往下移一行";
                case XtraRichEditStringId.FieldLastName: return "姓";
                case XtraRichEditStringId.DefaultStyleName_pagenumber: return "页码";
                case XtraRichEditStringId.DefaultStyleName_heading6: return "标题 6";
                case XtraRichEditStringId.MenuCmd_IncrementIndent: return "增加段落的缩排层级.";
                case XtraRichEditStringId.DefaultStyleName_TableSimple2: return "表格 简易 2";
                case XtraRichEditStringId.MenuCmd_MovePreviousWordDescription: return "移到上一个字符";
                case XtraRichEditStringId.Msg_InvalidCopyFromDocumentModel: return "错误: 来源及目标模块不相同";
                case XtraRichEditStringId.MenuCmd_InsertFieldDescription: return "插入字段";
                case XtraRichEditStringId.DefaultStyleName_List2: return "清单 2";
                case XtraRichEditStringId.MenuCmd_DeleteWordBackDescription: return "删除字符并往回";
                case XtraRichEditStringId.MenuCmd_FindAndSelectBackwardDescription: return "在选取项目中向上寻找";
                case XtraRichEditStringId.FieldMapEMailAddress: return "电子邮件信箱";
                case XtraRichEditStringId.MenuCmd_InsertColumnBreak: return "插入分栏符";
                case XtraRichEditStringId.MenuCmd_SelectAllDescription: return "全选";
                case XtraRichEditStringId.FieldMapAddress3: return "地址 3";
                case XtraRichEditStringId.DefaultStyleName_TableGrid7: return "表格 网格线 7";
                case XtraRichEditStringId.MenuCmd_InsertOpeningSingleQuotationMarkDescription: return "插入开头单引号";
                case XtraRichEditStringId.DefaultStyleName_HTMLPreformatted: return "HTML Preformatted ";
                case XtraRichEditStringId.MenuCmd_InsertOpeningSingleQuotationMark: return "插入开头单引号";
                case XtraRichEditStringId.DefaultStyleName_footnotetext: return "注尾文字";
                case XtraRichEditStringId.Msg_SyntaxErrorInFieldPattern: return "字段的设定程序文法错误, {0}.";
                case XtraRichEditStringId.FileFilterDescription_MhtFiles: return "单一网页档案";
                case XtraRichEditStringId.MenuCmd_InsertPageBreakDescription: return "在目前位置插入一个分页符号.";
                case XtraRichEditStringId.DefaultStyleName_HTMLDefinition: return "HTML Definition ";
                case XtraRichEditStringId.MenuCmd_Zoom: return "缩放";
                case XtraRichEditStringId.DefaultStyleName_TableList3: return "表格 列表 3";
                case XtraRichEditStringId.DefaultStyleName_index2: return "索引 2";
                case XtraRichEditStringId.MenuCmd_DeleteCoreDescription: return "删除核心";
                case XtraRichEditStringId.DefaultStyleName_List3: return "清单 3";
                case XtraRichEditStringId.Msg_InvalidParagraphContainNumbering: return "错误: 段落已包含号编号项目";
                case XtraRichEditStringId.MenuCmd_FontSuperscriptDescription: return "将文字缩小并移到该行的文字线的上方.";
                case XtraRichEditStringId.FieldMapPartnerLastName: return "配偶/父母 姓";
                case XtraRichEditStringId.DefaultStyleName_TableList2: return "表格 列表 2";
                case XtraRichEditStringId.DefaultStyleName_toc7: return "内文 7";
                case XtraRichEditStringId.DefaultStyleName_TableGrid4: return "表格 网格线 4";
                case XtraRichEditStringId.MenuCmd_MoveScreenDown: return "往下移动一个屏幕显示的范围";
                case XtraRichEditStringId.DefaultStyleName_index4: return "索引 4";
                case XtraRichEditStringId.FileFilterDescription_RtfFiles: return "RTF 格式";
                case XtraRichEditStringId.DefaultStyleName_ListNumber2: return "列表编号符号 2";
                case XtraRichEditStringId.MenuCmd_MoveToStartOfLineDescription: return "移至此行的开头";
                case XtraRichEditStringId.MenuCmd_ShiftTabKeyDescription: return "ShiftTab 键";
                case XtraRichEditStringId.MenuCmd_SelectFieldPrevToCaretDescription: return "将游标移至上一个字段";
                case XtraRichEditStringId.UnitAbbreviation_Centimeter: return " 公分";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentJustifyDescription: return "将文字对齐左右两边边界, 必要时在每个字相隔之间增加空白间隔.此项功能能帮您将文字自动延伸至左右两边边界, 并自动增加间隔.";
                case XtraRichEditStringId.DefaultStyleName_TableGrid1: return "表格 网格线 1";
                case XtraRichEditStringId.MenuCmd_ReplaceDescription: return "在文件中取代符合条件的字符.";
                case XtraRichEditStringId.DefaultStyleName_Table3Deffects1: return "表格 3D 效果 1";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentLeftDescription: return "将文字靠左对齐.";
                case XtraRichEditStringId.DefaultStyleName_TableSubtle1: return "表格 简易 1";
                case XtraRichEditStringId.MenuCmd_ScrollDownDescription: return "往下卷动";
                case XtraRichEditStringId.MenuCmd_DeleteWordBack: return "删除字符并往回";
                case XtraRichEditStringId.MenuCmd_InsertMergeField: return "插入合并域";
                case XtraRichEditStringId.DefaultStyleName_indexheading: return "标题索引";
                case XtraRichEditStringId.DefaultStyleName_ListContinue3: return "接续 3";
                case XtraRichEditStringId.MenuCmd_InsertCopyrightSymbolDescription: return "插入 Copyright 版权符号";
                case XtraRichEditStringId.DefaultStyleName_ListContinue2: return "接续 2";
                case XtraRichEditStringId.DefaultStyleName_TableGrid8: return "表格 网格线 8";
                case XtraRichEditStringId.MenuCmd_ChangeStyle: return "快速样式";
                case XtraRichEditStringId.MenuCmd_MoveNextPage: return "移到下一页";
                case XtraRichEditStringId.DefaultStyleName_TableColorful1: return "表格 色彩 1";
                case XtraRichEditStringId.FieldMapPartnerFirstName: return "配偶/父母 名";
                case XtraRichEditStringId.Msg_InvalidEndUpdate: return "错误: 在执行「BeginInit」或是「BeginUpdate」呼叫「EndUpdate」或是「CancelUpate」程序时发生错误";
                case XtraRichEditStringId.MenuCmd_SelectAll: return "全选";
                case XtraRichEditStringId.MenuCmd_DeleteBackCore: return "删除并往回核心";
                case XtraRichEditStringId.MenuCmd_DeleteWordBackCoreDescription: return "删除字符并往回";
                case XtraRichEditStringId.DefaultStyleName_heading5: return "标题 5";
                case XtraRichEditStringId.DefaultStyleName_index1: return "索引 1";
                case XtraRichEditStringId.DefaultStyleName_PlainText: return "纯文本";
                case XtraRichEditStringId.MenuCmd_MoveToEndOfLineDescription: return "移至此行的结尾";
                case XtraRichEditStringId.MenuCmd_SelectFieldPrevToCaret: return "将游标移至上一个字段";
                case XtraRichEditStringId.Msg_InvalidParentStyle: return "错误: 样式的继承来源无效, 其原因为会构成参考的无限循环";
                case XtraRichEditStringId.DefaultStyleName_HTMLAddress: return "HTML Address ";
                case XtraRichEditStringId.MenuCmd_LoadDocumentDescription: return "开启文件";
                case XtraRichEditStringId.MenuCmd_DraftView: return "草案检视";
                case XtraRichEditStringId.MenuCmd_DecrementNumerationFromParagraphDescription: return "减少段落中的编号数字";
                case XtraRichEditStringId.MenuCmd_FindAndSelectForward: return "在选取项目中向下寻找";
                case XtraRichEditStringId.DefaultStyleName_HTMLTypewriter: return "HTML Typewriter ";
                case XtraRichEditStringId.FontStyle_Strikeout: return "删除线";
                case XtraRichEditStringId.DefaultStyleName_TableGrid: return "表格 网格线 ";
                case XtraRichEditStringId.MenuCmd_FindPrevDescription: return "往回取代最近找到符合条件的字符.";
                case XtraRichEditStringId.FontStyle_BoldItalic: return "粗斜体";
                case XtraRichEditStringId.MenuCmd_ToggleHiddenText: return "隐藏";
                case XtraRichEditStringId.DefaultStyleName_BodyText: return "本文文字";
                case XtraRichEditStringId.DefaultStyleName_envelopeaddress: return "信封地址";
                case XtraRichEditStringId.MenuCmd_IncrementNumerationFromParagraph: return "增加段落中的编号数字";
                case XtraRichEditStringId.MenuCmd_MoveScreenUpDescription: return "往上移动一个屏幕显示的范围";
                case XtraRichEditStringId.MenuCmd_ReplaceAllBackward: return "往上取代全部";
                case XtraRichEditStringId.DefaultStyleName_ListContinue5: return "接续 5";
                case XtraRichEditStringId.FieldMapCompany: return "公司";
                case XtraRichEditStringId.DefaultStyleName_annotationreference: return "脚注引用";
                case XtraRichEditStringId.DefaultStyleName_HTMLKeyboard: return "HTML Keyboard ";
                case XtraRichEditStringId.Caption_AlignmentLeft: return "靠左对齐";
                case XtraRichEditStringId.FieldMapMiddleName: return "名字";
                case XtraRichEditStringId.MenuCmd_DecrementFontSizeDescription: return "减少字体大小";
                case XtraRichEditStringId.Msg_SearchComplete: return "寻找完毕.";
                case XtraRichEditStringId.MenuCmd_ReplaceAllForwardDescription: return "往下取代全部";
                case XtraRichEditStringId.MenuCmd_ScrollDown: return "往下卷动";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldCodes: return "显示所有字段代码";
                case XtraRichEditStringId.ClearFormatting: return "清除格式";
                case XtraRichEditStringId.MenuCmd_InsertField: return "插入字段";
                case XtraRichEditStringId.DefaultStyleName_TableColumns5: return "表格 栏5";
                case XtraRichEditStringId.MenuCmd_InsertSimpleListDescription: return "插入编号符号.";
                case XtraRichEditStringId.DefaultStyleName_envelopereturn: return "回函信封";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleStrikeout: return "双删除线";
                case XtraRichEditStringId.MenuCmd_ToggleWhitespace: return "显示/隐藏 ¶";
                case XtraRichEditStringId.MenuCmd_MoveLineDownDescription: return "往下移一行";
                case XtraRichEditStringId.DefaultStyleName_toc3: return "内文 3";
                case XtraRichEditStringId.MenuCmd_ChangeFontName: return "字型";
                case XtraRichEditStringId.DefaultStyleName_TableClassic3: return "表格 古典 3";
                case XtraRichEditStringId.Msg_InvalidSetParagraphProperties: return "错误: 无法在未初起化或文件中没有对象的情形下设定段落属性";
                case XtraRichEditStringId.Msg_UseDeletedStyleError: return "错误: 使用删除样式";
                case XtraRichEditStringId.DefaultStyleName_ListNumber4: return "列表编号符号 4";
                case XtraRichEditStringId.DefaultStyleName_NormalIndent: return "一般缩排";
                case XtraRichEditStringId.FieldMapPhoneticGuideLastName: return "姓氏的拼音指南";
                case XtraRichEditStringId.MenuCmd_InsertMultilevelListDescription: return "插入阶层式编号符号.";
                case XtraRichEditStringId.MenuCmd_ToggleViewMergedDataDescription: return "将实际数据依字段所设定的代码填入文件中所指定的字段, 并完整的显示出来.";
                case XtraRichEditStringId.MenuCmd_ToggleFontUnderline: return "底线";
                case XtraRichEditStringId.MenuCmd_FontSubscriptDescription: return "将文字缩小并移到该行的文字线的下方.";
                case XtraRichEditStringId.MenuCmd_TabKey: return "Tab 键";
                case XtraRichEditStringId.DefaultStyleName_BalloonText: return "强调文字";
                case XtraRichEditStringId.MenuCmd_ChangeColumnCount: return "数据域";
                case XtraRichEditStringId.DefaultStyleName_TableColumns2: return "表格 栏2";
                case XtraRichEditStringId.MenuCmd_SaveDocument: return "储存文件";
                case XtraRichEditStringId.MenuCmd_ScrollToPage: return "卷动至页面";
                case XtraRichEditStringId.MenuCmd_InsertLineBreak: return "插入跳行字符";
                case XtraRichEditStringId.Msg_InvalidBeginUpdate: return "错误: 开始初始化中呼叫「BeginUpdate」程序时发生错误";
                case XtraRichEditStringId.MenuCmd_IncrementNumerationFromParagraphDescription: return "增加段落中的编号数字";
                case XtraRichEditStringId.Caption_AlignmentCenter: return "置中";
                case XtraRichEditStringId.DefaultStyleName_heading4: return "标题 4";
                case XtraRichEditStringId.DefaultStyleName_Closing: return "关闭中";
                case XtraRichEditStringId.DefaultStyleName_TableWeb3: return "表格 Web 3";
                case XtraRichEditStringId.DefaultStyleName_BodyTextFirstIndent: return "本文第一层缩排";
                case XtraRichEditStringId.MenuCmd_InsertText: return "插入文字";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldResults: return "显示所有字段结果";
                case XtraRichEditStringId.Msg_UnmatchedQuotesInFieldPattern: return "错误: 字段的设定程序里引号数不对称.";
                case XtraRichEditStringId.Msg_UseInvalidCharacterProperties: return "错误: 字符属性不再有效";
                case XtraRichEditStringId.DefaultStyleName_footnotereference: return "注尾参考";
                case XtraRichEditStringId.MenuCmd_SelectFieldNextToCaret: return "将游标移至下一个字段";
                case XtraRichEditStringId.MenuCmd_ChangeStyleDescription: return "透过缩图快速挑选样式来设定格式、抬头、标点符号等等.";
                case XtraRichEditStringId.Msg_ContinueSearchInRemainderQuestion: return "您想要再寻找一次文件的其他部份吗?";
                case XtraRichEditStringId.DefaultStyleName_caption: return "说明文字";
                case XtraRichEditStringId.DefaultStyleName_tableofauthorities: return "权限表";
                case XtraRichEditStringId.DefaultStyleName_Subtitle: return "子标题";
                case XtraRichEditStringId.MenuCmd_InsertMultilevelList: return "阶层式编号符号";
                case XtraRichEditStringId.Caption_LineSpacingSingle: return "单行间距";
                case XtraRichEditStringId.DefaultStyleName_HyperlinkStrongEmphasis: return "强调式超链接";
                case XtraRichEditStringId.MenuCmd_ReplaceBackward: return "向上取代";
                case XtraRichEditStringId.MenuCmd_DecrementIndent: return "减少缩排";
                case XtraRichEditStringId.DefaultStyleName_endnotereference: return "注尾引用";
                case XtraRichEditStringId.DefaultStyleName_heading1: return "标题 1";
                case XtraRichEditStringId.TabForm_All: return "全部";
                case XtraRichEditStringId.DefaultStyleName_toc2: return "内文 2";
                case XtraRichEditStringId.DefaultStyleName_HTMLVariable: return "HTML Variable ";
                case XtraRichEditStringId.FieldMapAddress1: return "地址 1";
                case XtraRichEditStringId.Msg_InvalidTabStop: return "定位点错误.";
                case XtraRichEditStringId.FieldMapPostalCode: return "邮政编码";
                case XtraRichEditStringId.DefaultStyleName_TableClassic1: return "表格 古典 1";
                case XtraRichEditStringId.DefaultStyleName_DocumentMap: return "文件索引";
                case XtraRichEditStringId.FieldMapPartnerNickName: return "配偶/父母 昵称";
                case XtraRichEditStringId.Msg_SearchInForwardDirectionComplete: return "已寻找到文件的结尾.";
                case XtraRichEditStringId.MenuCmd_IncrementIndentDescription: return "增加段落的缩排层级.";
                case XtraRichEditStringId.MenuCmd_InsertTrademarkSymbol: return "插入商标符号";
                case XtraRichEditStringId.MenuCmd_ToggleFontStrikeout: return "删除线";
                case XtraRichEditStringId.DefaultStyleName_Signature: return "签名";
                case XtraRichEditStringId.MenuCmd_DeleteWordDescription: return "删除字符";
                case XtraRichEditStringId.MenuCmd_Redo: return "重做";
                case XtraRichEditStringId.Caption_FirstLineIndentHanging: return "凸排";
                case XtraRichEditStringId.MenuCmd_DeleteBack: return "删除并往回";
                case XtraRichEditStringId.MenuCmd_DecrementIndentDescription: return "减少段落的缩排层级..";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphStyle: return "变更段落样式";
                case XtraRichEditStringId.MenuCmd_DeleteWordCoreDescription: return "删除字符核心";
                case XtraRichEditStringId.MenuCmd_FindNextDescription: return "向下取代最近找到符合条件的字符.";
                case XtraRichEditStringId.MenuCmd_ChangeColumnCountDescription: return "数据域";
                case XtraRichEditStringId.Msg_ContinueSearchFromBeginningQuestion: return "您想要从文件的开头再寻找一次吗?";
                case XtraRichEditStringId.DefaultStyleName_TableList5: return "表格 列表 5";
                case XtraRichEditStringId.FieldMapDepartment: return "部门";
                case XtraRichEditStringId.Caption_LineSpacingDouble: return "2 倍行高";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentJustify: return "两端对齐";
                case XtraRichEditStringId.MenuCmd_UndoDescription: return "复原";
                case XtraRichEditStringId.MenuCmd_HighlightTextDescription: return "让文字看起来像是被荧光笔标示.";
                case XtraRichEditStringId.Caption_LineSpacingExactly: return "固定行高";
                case XtraRichEditStringId.DefaultStyleName_TableColorful3: return "表格 色彩 3";
                case XtraRichEditStringId.Msg_InternalError: return "发生内部错误";
                case XtraRichEditStringId.MenuCmd_InsertMergeFieldDescription: return "插入合并域";
                case XtraRichEditStringId.MenuCmd_ChangeFontSizeDescription: return "变更字型的大小.";
                case XtraRichEditStringId.MenuCmd_MoveForward: return "前进";
                case XtraRichEditStringId.MenuCmd_CopySelectionDescription: return "将所选择的项目复制到系统剪贴簿内.";
                case XtraRichEditStringId.DefaultStyleName_ListNumber5: return "列表编号符号 5";
                case XtraRichEditStringId.MenuCmd_ClearFormatting: return "清除格式";
                case XtraRichEditStringId.DefaultStyleName_toc8: return "内文 8";
                case XtraRichEditStringId.MenuCmd_InsertNonBreakingSpace: return "插入接续本页符号";
                case XtraRichEditStringId.Msg_UseDeletedSectionError: return "错误: 使用删除部份";
                case XtraRichEditStringId.MenuCmd_MoveBackwardDescription: return "后退";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldResultsDescription: return "显示所有字段结果";
                case XtraRichEditStringId.MenuCmd_DecreaseFontSizeDescription: return "减少字号.";
                case XtraRichEditStringId.Msg_ReplacementsCount: return "已完成取代了 {0} 个项目.";
                case XtraRichEditStringId.MenuCmd_ToggleFontItalicDescription: return "让所选定的文字倾斜.";
                case XtraRichEditStringId.FileFilterDescription_AllSupportedFiles: return "所有支持格式的档案";
                case XtraRichEditStringId.MenuCmd_ChangeFontColor: return "字型颜色";
                case XtraRichEditStringId.Msg_PrintingUnavailable: return "无法打印. 请检查下列的程序文件是否安装:{0}{1}";
                case XtraRichEditStringId.MenuCmd_InsertRegisteredTrademarkSymbol: return "插入注册商标符号";
                case XtraRichEditStringId.Msg_ZeroDivide: return "!分母不可为零.";
                case XtraRichEditStringId.MenuCmd_MoveToBeginOfDocumentDescription: return "移至文件的开头";
                case XtraRichEditStringId.DefaultStyleName_HTMLCite: return "HTML Cite ";
                case XtraRichEditStringId.FieldMapFirstName: return "名";
                case XtraRichEditStringId.MenuCmd_IncreaseFontSizeDescription: return "增加字号.";
                case XtraRichEditStringId.FontStyle_Regular: return "平均分散";
                case XtraRichEditStringId.DefaultStyleName_index5: return "索引 5";
                case XtraRichEditStringId.MenuCmd_PlaceCaretToPhysicalPointDescription: return "将游标移至实际的像素点";
                case XtraRichEditStringId.MenuCmd_HighlightText: return "文字高亮颜色";
                case XtraRichEditStringId.MenuCmd_SaveDocumentAs: return "另存新檔";
                case XtraRichEditStringId.DefaultStyleName_Table3Deffects3: return "表格 3D 效果 3";
                case XtraRichEditStringId.DefaultStyleName_TableSimple1: return "表格 简易 1";
                case XtraRichEditStringId.MenuCmd_MovePreviousParagraph: return "移到上一个段落";
                case XtraRichEditStringId.MenuCmd_MoveToEndOfDocument: return "移至文件的结尾";
                case XtraRichEditStringId.Msg_UseDeletedParagraphError: return "错误: 使用删除段落";
                case XtraRichEditStringId.DefaultStyleName_ListNumber3: return "列表编号符号 3";
                case XtraRichEditStringId.FileFilterDescription_PNGFiles: return "PNG 影像格式";
                case XtraRichEditStringId.MenuCmd_ReplaceForward: return "向下取代";
                case XtraRichEditStringId.MenuCmd_ShowInsertMergeFieldFormDescription: return "从数据表或是数据源新增一个字段到文件中.";
                case XtraRichEditStringId.MenuCmd_Undo: return "复原";
                case XtraRichEditStringId.MenuCmd_MoveToEndOfDocumentDescription: return "移至文件的结尾";
                case XtraRichEditStringId.MenuCmd_DecrementFontSize: return "减少字体大小";
                case XtraRichEditStringId.DefaultStyleName_Normal: return "一般 ";
                case XtraRichEditStringId.Msg_SearchItemNotFound: return "没有找到符合条件的项目.";
                case XtraRichEditStringId.MenuCmd_TabKeyDescription: return "Tab 键";
                case XtraRichEditStringId.MenuCmd_Print: return "打印(&P)";
                case XtraRichEditStringId.MenuCmd_SetSingleParagraphSpacingDescription: return "设置单一段落的间距";
                case XtraRichEditStringId.MenuCmd_MoveToEndOfLine: return "移至此行的结尾";
                case XtraRichEditStringId.DefaultStyleName_toc6: return "内文 6";
                case XtraRichEditStringId.DefaultStyleName_NoList: return "无清单";
                case XtraRichEditStringId.FileFilterDescription_TextFiles: return "文本文件";
                case XtraRichEditStringId.MenuCmd_ClearFormattingDescription: return "清除所选区域内的所有格式, 回复成纯文本样式.";
                case XtraRichEditStringId.MenuCmd_ToggleFontStrikeoutDescription: return "在所选定的文字中间绘出直线.";
                case XtraRichEditStringId.DefaultStyleName_index9: return "索引 9";
                case XtraRichEditStringId.DefaultStyleName_HTMLCode: return "HTML Code ";
                case XtraRichEditStringId.Msg_UnknownSwitchArgument: return "错误! 不知名的切换参数.";
                case XtraRichEditStringId.FileFilterDescription_OpenXmlFiles: return "Word 2007 文件";
                case XtraRichEditStringId.LinkedCharacterStyleFormatString: return "{0} 个字符";
                case XtraRichEditStringId.MenuCmd_DecrementParagraphLeftIndent: return "减少段落左方缩排";
                case XtraRichEditStringId.MenuCmd_IncrementParagraphLeftIndentDescription: return "增加段落左方缩排";
                case XtraRichEditStringId.DefaultStyleName_NormalWeb: return "一般 (Web)";
                case XtraRichEditStringId.DefaultStyleName_TableProfessional: return "表格 专业";
                case XtraRichEditStringId.MenuCmd_FindAndSelectBackward: return "在选取项目中向上寻找";
                case XtraRichEditStringId.DefaultStyleName_index8: return "索引 8";
                case XtraRichEditStringId.MenuCmd_EnsureCaretVisibleHorizontallyDescription: return "将插入号水平显示";
                case XtraRichEditStringId.MenuCmd_MoveToBeginOfDocument: return "移至文件的开头";
                case XtraRichEditStringId.MenuCmd_PlaceCaretToPhysicalPoint: return "将游标移至实际的像素点";
                case XtraRichEditStringId.MenuCmd_ChangeParagraphStyleDescription: return "变更段落样式";
                case XtraRichEditStringId.MenuCmd_InsertRegisteredTrademarkSymbolDescription: return "插入注册商标符号";
                case XtraRichEditStringId.ColorAuto: return "自动";
                case XtraRichEditStringId.DefaultStyleName_BlockText: return "文字框";
                case XtraRichEditStringId.MenuCmd_InsertBulletList: return "项目符号";
                case XtraRichEditStringId.MenuCmd_LoadDocument: return "开启文件";
                case XtraRichEditStringId.DefaultStyleName_TableList4: return "表格 列表 4";
                case XtraRichEditStringId.MenuCmd_ReplaceAllBackwardDescription: return "往上取代全部";
                case XtraRichEditStringId.DefaultStyleName_TableGrid5: return "表格 网格线 5";
                case XtraRichEditStringId.Caption_FirstLineIndentNone: return "(无)";
                case XtraRichEditStringId.FileFilterDescription_JPEGFiles: return "JPEG 影像格式";
                case XtraRichEditStringId.MenuCmd_ShowParagraphForm: return "段落";
                case XtraRichEditStringId.MenuCmd_DeleteNumerationFromParagraph: return "从段落中删除编号数字";
                case XtraRichEditStringId.DefaultStyleName_TableWeb1: return "表格 Web 1";
                case XtraRichEditStringId.MenuCmd_PrintDescription: return "在打印前选择列表机, 份数以及其他的打印选项.";
                case XtraRichEditStringId.MenuCmd_ChangeFontSize: return "字号";
                case XtraRichEditStringId.FileFilterDescription_BitmapFiles: return "位图";
                case XtraRichEditStringId.DefaultStyleName_endnotetext: return "注尾文字";
                case XtraRichEditStringId.DefaultStyleName_ListContinue4: return "接续 4";
                case XtraRichEditStringId.MenuCmd_DeleteNumerationFromParagraphDescription: return "从段落中删除编号数字";
                case XtraRichEditStringId.DefaultStyleName_toc5: return "内文 5";
                case XtraRichEditStringId.DefaultStyleName_TableList6: return "表格 列表 6";
                case XtraRichEditStringId.MenuCmd_ToggleFontItalic: return "斜体";
                case XtraRichEditStringId.MenuCmd_Paste: return "贴上";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentCenterDescription: return "将文字置中.";
                case XtraRichEditStringId.MenuCmd_PrintView: return "打印检视";
                case XtraRichEditStringId.MenuCmd_UpdateField: return "更新字段";
                case XtraRichEditStringId.MenuCmd_PasteDescription: return "将剪贴簿上的内容贴上在目前的位置.";
                case XtraRichEditStringId.Msg_InvalidBeginInit: return "错误: 开始更新中呼叫「BeginInit」程序时发生错误";
                case XtraRichEditStringId.MenuCmd_MoveNextParagraphDescription: return "移到下一个段落";
                case XtraRichEditStringId.MenuCmd_ChangeIndentDescription: return "变更缩排";
                case XtraRichEditStringId.MenuCmd_Find: return "寻找";
                case XtraRichEditStringId.FieldMapWebPage: return "网页档案";
                case XtraRichEditStringId.FieldMapCountry: return "国家或地区";
                case XtraRichEditStringId.MenuCmd_InsertTextDescription: return "插入文字";
                case XtraRichEditStringId.Msg_InvalidFontSize: return "字号需介于 {0} 与 {1} 之间.";
                case XtraRichEditStringId.MenuCmd_InsertOpeningDoubleQuotationMarkDescription: return "插入开头双引号";
                case XtraRichEditStringId.MenuCmd_InsertColumnBreakDescription: return "插入分栏符";
                case XtraRichEditStringId.MenuCmd_MovePreviousPage: return "移到上一页";
                case XtraRichEditStringId.MenuCmd_BackSpaceKey: return "BackSpace 键";
                case XtraRichEditStringId.MenuCmd_ReplaceAllForward: return "往下取代全部";
                case XtraRichEditStringId.MenuCmd_UpdateFieldDescription: return "更新字段";
                case XtraRichEditStringId.MenuCmd_ToggleFontBold: return "粗体";
                case XtraRichEditStringId.Msg_UnexpectedEndOfFormula: return "!公式于不可预期的情形下结束.";
                case XtraRichEditStringId.FontStyle_Underline: return "底线";
                case XtraRichEditStringId.MenuCmd_SimpleViewDescription: return "简易检视";
                case XtraRichEditStringId.MenuCmd_SimpleView: return "简易检视";
                case XtraRichEditStringId.DefaultStyleName_Title: return "标题";
                case XtraRichEditStringId.MenuCmd_ReadingViewDescription: return "阅读视图";
                case XtraRichEditStringId.FieldMapHomePhone: return "住家电话";
                case XtraRichEditStringId.MenuCmd_InsertEllipsisDescription: return "插入省略号";
                case XtraRichEditStringId.DefaultStyleName_heading7: return "标题 7";
                case XtraRichEditStringId.MenuCmd_InsertPictureDescription: return "选择图片档案并插入文件中.";
                case XtraRichEditStringId.MenuCmd_DeleteWord: return "删除字符";
                case XtraRichEditStringId.FileFilterDescription_AllFiles: return "全部档案";
                case XtraRichEditStringId.MenuCmd_DeleteWordBackCore: return "删除字符并往回";
                case XtraRichEditStringId.DefaultStyleName_ListBullet3: return "列表项目符号 3";
                case XtraRichEditStringId.MenuCmd_InsertClosingDoubleQuotationMark: return "插入结尾双引号";
                case XtraRichEditStringId.Msg_SearchInBackwardDirectionComplete: return "已寻找到文件的开头.";
                case XtraRichEditStringId.Msg_SearchInSelectionComplete: return "已完成在选定范围内的寻找.";
                case XtraRichEditStringId.DefaultStyleName_toc9: return "内文 9";
                case XtraRichEditStringId.DefaultStyleName_annotationsubject: return "注释标题";
                case XtraRichEditStringId.DefaultStyleName_TableList8: return "表格 列表 8";
                case XtraRichEditStringId.MenuCmd_SelectFieldNextToCaretDescription: return "将游标移至下一个字段";
                case XtraRichEditStringId.Msg_IsNotValid: return "'{0}' 不是 '{1}' 有效的值";
                case XtraRichEditStringId.DefaultStyleName_ListBullet5: return "列表项目符号 5";
                case XtraRichEditStringId.MenuCmd_InsertClosingDoubleQuotationMarkDescription: return "插入结尾双引号";
                case XtraRichEditStringId.MenuCmd_DecrementNumerationFromParagraph: return "减少段落中的编号数字";
                case XtraRichEditStringId.MenuCmd_InsertOpeningDoubleQuotationMark: return "插入开头双引号";
                case XtraRichEditStringId.DefaultStyleName_TableColorful2: return "表格 色彩 2";
                case XtraRichEditStringId.Msg_ContinueSearchFromEndQuestion: return "您想要从文件的结尾再寻找一次吗?";
                case XtraRichEditStringId.Msg_StyleAlreadyLinked: return "错误: 样式里已经包含了一组连接样式";
                case XtraRichEditStringId.FieldMapBusinessPhone: return "商务电话";
                case XtraRichEditStringId.MenuCmd_SaveDocumentDescription: return "储存文件";
                case XtraRichEditStringId.MenuCmd_DecreaseFontSize: return "字型缩小";
                case XtraRichEditStringId.MenuCmd_InsertParagraph: return "插入段落";
                case XtraRichEditStringId.MenuCmd_InsertEnDash: return "插入破折号";
                case XtraRichEditStringId.DefaultStyleName_OutlineList2: return "大纲清单 2";
                case XtraRichEditStringId.DefaultStyleName_TableClassic4: return "表格 古典 4";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleStrikeoutDescription: return "在所选定的文字中间绘出二条直线";
                case XtraRichEditStringId.DefaultStyleName_Date: return "日期";
                case XtraRichEditStringId.MenuCmd_NewEmptyDocument: return "新增文件";
                case XtraRichEditStringId.DefaultStyleName_List: return "清单";
                case XtraRichEditStringId.MenuCmd_MoveForwardDescription: return "前进";
                case XtraRichEditStringId.Msg_MissingOperator: return "!遗漏了运算符.";
                case XtraRichEditStringId.DefaultStyleName_heading3: return "标题 3";
                case XtraRichEditStringId.FileFilterDescription_HtmlFiles: return "HTML 网页档案";
                case XtraRichEditStringId.Caption_AlignmentJustify: return "两端对齐";
                case XtraRichEditStringId.DialogCaption_InsertSymbol: return "符号";
                case XtraRichEditStringId.DefaultStyleName_ListNumber: return "列表编号符号 ";
                case XtraRichEditStringId.DefaultStyleName_List4: return "清单 4";
                case XtraRichEditStringId.DefaultStyleName_TableSimple3: return "表格 简易 3";
                case XtraRichEditStringId.MenuCmd_DecrementParagraphLeftIndentDescription: return "减少段落左方缩排";
                case XtraRichEditStringId.MenuCmd_MoveBackward: return "后退";
                case XtraRichEditStringId.MenuCmd_ZoomOutDescription: return "拉远";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleUnderlineDescription: return "让所选定的文字出现双底线";
                case XtraRichEditStringId.DefaultStyleName_TableGrid2: return "表格 网格线 2";
                case XtraRichEditStringId.MenuCmd_Delete: return "删除";
                case XtraRichEditStringId.MenuCmd_ReplaceTextDescription: return "取代文字";
                case XtraRichEditStringId.FieldMapJobTitle: return "职称";
                case XtraRichEditStringId.MenuCmd_SaveDocumentAsDescription: return "另存新檔";
                case XtraRichEditStringId.MenuCmd_InsertParagraphDescription: return "插入段落";
                case XtraRichEditStringId.DefaultStyleName_index6: return "索引 6";
                case XtraRichEditStringId.MenuCmd_MovePreviousWord: return "移到上一个字符";
                case XtraRichEditStringId.MenuCmd_RedoDescription: return "重做";
                case XtraRichEditStringId.DefaultStyleName_toc1: return "内文 1";
                case XtraRichEditStringId.DefaultStyleName_heading9: return "标题 9";
                case XtraRichEditStringId.MenuCmd_InsertLineBreakDescription: return "插入跳行字符";
                case XtraRichEditStringId.MenuCmd_FindNext: return "找下一个";
                case XtraRichEditStringId.MenuCmd_FindAndSelectForwardDescription: return "在选取项目中向下寻找";
                case XtraRichEditStringId.DefaultStyleName_NoteHeading: return "注释标题";
                case XtraRichEditStringId.DefaultStyleName_TableSubtle2: return "表格 简易 2";
                case XtraRichEditStringId.DefaultStyleName_List5: return "清单 5";
                case XtraRichEditStringId.MenuCmd_InsertClosingSingleQuotationMark: return "插入结尾单引号";
                case XtraRichEditStringId.MenuCmd_MoveNextWord: return "移到下一个字符";
                case XtraRichEditStringId.Msg_InvalidDocumentModel: return "错误: 文件模块不相同";
                case XtraRichEditStringId.MenuCmd_IncreaseFontSize: return "增加字号.";
                case XtraRichEditStringId.MenuCmd_QuickPrint: return "直接打印(&Q)";
                case XtraRichEditStringId.MenuCmd_PrintPreview: return "打印预览(&v)";
                case XtraRichEditStringId.Caption_LineSpacingMultiple: return "多行";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentLeft: return "靠左对齐";
                case XtraRichEditStringId.DefaultStyleName_DefaultParagraphFont: return "默认段落字型";
                case XtraRichEditStringId.MenuCmd_ZoomOut: return "拉远";
                case XtraRichEditStringId.MenuCmd_CreateFieldDescription: return "建立字段";
                case XtraRichEditStringId.MenuCmd_CutSelection: return "剪下";
                case XtraRichEditStringId.MenuCmd_SetSingleParagraphSpacing: return "设置单一段落的间距";
                case XtraRichEditStringId.MenuCmd_ShowFontFormDescription: return "显示字型对话框.";
                case XtraRichEditStringId.Msg_UnsupportedFormatException: return "文件格式不支持";
                case XtraRichEditStringId.FieldMapBusinessFax: return "商务传真";
                case XtraRichEditStringId.MenuCmd_InsertPageBreak: return "分页符号";
                case XtraRichEditStringId.DefaultStyleName_BodyText2: return "本文文字 2";
                case XtraRichEditStringId.DefaultStyleName_toc4: return "内文 4";
                case XtraRichEditStringId.MenuCmd_DeleteCore: return "删除核心";
                case XtraRichEditStringId.Msg_InvalidEndInit: return "错误: 开始初始化中呼叫「BeginUpdate」程序时发生错误";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentCenter: return "置中";
                case XtraRichEditStringId.MenuCmd_ToggleFieldCodes: return "切换字段代码";
                case XtraRichEditStringId.MenuCmd_FindPrev: return "向上寻找";
                case XtraRichEditStringId.MenuCmd_ToggleViewMergedData: return "检视组合后的数据";
                case XtraRichEditStringId.MenuCmd_ChangeCharacterStyle: return "变更字符样式";
                case XtraRichEditStringId.MenuCmd_ToggleFontBoldDescription: return "让所选定的文字变粗.";
                case XtraRichEditStringId.MenuCmd_MoveNextParagraph: return "移到下一个段落";
                case XtraRichEditStringId.MenuCmd_BackSpaceKeyDescription: return "BackSpace 键";
                case XtraRichEditStringId.FieldMapPartnerTitle: return "配偶/父母 尊称";
                case XtraRichEditStringId.UnderlineNone: return "(无)";
                case XtraRichEditStringId.DefaultStyleName_TableContemporary: return "表格 现代";
                case XtraRichEditStringId.FieldMapPhoneticGuideFirstName: return "名字的拼音指南";
                case XtraRichEditStringId.Msg_UseInvalidParagraphProperties: return "错误: 段落属性不再有效";
                case XtraRichEditStringId.DefaultStyleName_index7: return "索引 7";
                case XtraRichEditStringId.MenuCmd_DeleteBackDescription: return "删除并往回";
                case XtraRichEditStringId.Msg_InvalidNumber: return "不是一个正确的数字.";
                case XtraRichEditStringId.MenuCmd_ToggleWhitespaceDescription: return "显示或隐藏段落标记及其他隐藏的格式标示符号.";
                case XtraRichEditStringId.MenuCmd_CreateField: return "建立字段";
                case XtraRichEditStringId.DefaultStyleName_linenumber: return "行号";
                case XtraRichEditStringId.MenuCmd_ScrollToPageDescription: return "卷动至页面";
                case XtraRichEditStringId.MenuCmd_Replace: return "取代";
                case XtraRichEditStringId.FieldMapPartnerMiddleName: return "配偶/父母 名字";
                case XtraRichEditStringId.MenuCmd_CopySelection: return "复制";
                case XtraRichEditStringId.MenuCmd_ChangeMistakenWordDescription: return "(没有拼写的建议)";
                case XtraRichEditStringId.MenuCmd_MoveToStartOfLine: return "移至此行的开头";
                case XtraRichEditStringId.DefaultStyleName_annotationtext: return "批注文字";
                case XtraRichEditStringId.MenuCmd_EnsureCaretVisibleHorizontally: return "将插入号水平显示";
                case XtraRichEditStringId.DefaultStyleName_TableColumns1: return "表格 栏1";
                case XtraRichEditStringId.MenuCmd_MoveNextPageDescription: return "移到下一页";
                case XtraRichEditStringId.MenuCmd_IncrementFontSize: return "增加字体大小";
                case XtraRichEditStringId.DefaultStyleName_header: return "表头";
                case XtraRichEditStringId.MenuCmd_ReadingView: return "阅读视图";
                case XtraRichEditStringId.MenuCmd_InsertClosingSingleQuotationMarkDescription: return "插入结尾单引号";
                case XtraRichEditStringId.DefaultStyleName_TableList1: return "表格 列表 1";
                case XtraRichEditStringId.Msg_ErrorLinkDeletedStyle: return "错误: 无法链接已删除的样式";
                case XtraRichEditStringId.Msg_InvalidStyleName: return "样式名称错误";
                case XtraRichEditStringId.DefaultStyleName_TableGrid6: return "表格 网格线 6";
                case XtraRichEditStringId.MenuCmd_DeleteBackCoreDescription: return "删除并往回核心";
                case XtraRichEditStringId.MenuCmd_ChangeIndent: return "变更缩排";
                case XtraRichEditStringId.Caption_LineSpacingSesquialteral: return "1.5 倍行高";
                case XtraRichEditStringId.MenuCmd_MoveScreenUp: return "往上移动一个屏幕显示的范围";
                case XtraRichEditStringId.DefaultStyleName_HTMLBottomofForm: return "HTML Bottom of Form ";
                case XtraRichEditStringId.MenuCmd_IncrementParagraphLeftIndent: return "增加段落左方缩排";
                case XtraRichEditStringId.DefaultStyleName_MessageHeader: return "讯息标题";
                case XtraRichEditStringId.MenuCmd_InsertEmDash: return "插入长破折号";
                case XtraRichEditStringId.MenuCmd_ChangeFontNameDescription: return "变更字型的字体.";
                case XtraRichEditStringId.MenuCmd_EnsureCaretVisibleVerticallyDescription: return "将插入号垂直显示";
                case XtraRichEditStringId.Caption_FirstLineIndentIndented: return "第一行";
                case XtraRichEditStringId.DefaultStyleName_tableoffigures: return "数字表格";
                case XtraRichEditStringId.DefaultStyleName_TableList7: return "表格 列表 7";
                case XtraRichEditStringId.MenuCmd_FindDescription: return "在文件中寻找符合条件的字符.";
                case XtraRichEditStringId.DefaultStyleName_HyperlinkFollowed: return "已查阅超链接";
                case XtraRichEditStringId.MenuCmd_FontSuperscript: return "上标";
                case XtraRichEditStringId.DefaultStyleName_TableElegant: return "表格 典雅";
                case XtraRichEditStringId.MenuCmd_InsertPicture: return "插入图片档案";
                case XtraRichEditStringId.MenuCmd_InsertSimpleList: return "编号符号";
                case XtraRichEditStringId.MenuCmd_MovePreviousPageDescription: return "移到上一页";
                case XtraRichEditStringId.MenuCmd_InsertCopyrightSymbol: return "插入 Copyright 版权符号";
                case XtraRichEditStringId.MenuCmd_InsertTabDescription: return "Insert键";
                case XtraRichEditStringId.DefaultStyleName_macrotoaheading: return "汇集到标题";
                case XtraRichEditStringId.MenuCmd_InsertEnDashDescription: return "插入破折号";
                case XtraRichEditStringId.DefaultStyleName_EmailSignature: return "电子邮件签名";
                case XtraRichEditStringId.DefaultStyleName_OutlineList1: return "大纲清单 1";
                case XtraRichEditStringId.FieldMapNickName: return "昵称";
                case XtraRichEditStringId.MenuCmd_ChangeMistakenWord: return "(没有拼写的建议)";
                case XtraRichEditStringId.DefaultStyleName_OutlineList3: return "大纲清单 3";
                case XtraRichEditStringId.MenuCmd_ZoomInDescription: return "拉近";
                case XtraRichEditStringId.MenuCmd_ToggleFontDoubleUnderline: return "双底线";
                case XtraRichEditStringId.MenuCmd_ToggleFontUnderlineDescription: return "让所选定的文字出现底线.";
                case XtraRichEditStringId.DefaultStyleName_TableGrid3: return "表格 网格线 3";
                case XtraRichEditStringId.MenuCmd_InsertEllipsis: return "插入省略号";
                case XtraRichEditStringId.MenuCmd_ZoomDescription: return "缩放";
                case XtraRichEditStringId.DefaultStyleName_TableWeb2: return "表格 Web 2";
                case XtraRichEditStringId.FieldMapHomeFax: return "住家传真";
                case XtraRichEditStringId.MenuCmd_IncrementFontSizeDescription: return "增加字体大小";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentRightDescription: return "将文字靠右对齐.";
                case XtraRichEditStringId.MenuCmd_PrintPreviewDescription: return "打印前预览要打印的结果画面.";
                case XtraRichEditStringId.MenuCmd_ReplaceBackwardDescription: return "向上取代";
                case XtraRichEditStringId.MenuCmd_ShowInsertMergeFieldForm: return "插入合并域";
                case XtraRichEditStringId.FieldMapState: return "省/州";
                case XtraRichEditStringId.DefaultStyleName_BodyTextFirstIndent2: return "本文第一层缩排 2";
                case XtraRichEditStringId.MenuCmd_InsertBulletListDescription: return "插入项目符号.";
                case XtraRichEditStringId.MenuCmd_PrintViewDescription: return "打印检视";
                case XtraRichEditStringId.MenuCmd_InsertTrademarkSymbolDescription: return "插入商标符号";
                case XtraRichEditStringId.DefaultStyleName_index3: return "索引 3";
                case XtraRichEditStringId.FieldMapSuffix: return "后缀语";
                case XtraRichEditStringId.DefaultStyleName_NormalTable: return "一般表格";
                case XtraRichEditStringId.FontStyle_Italic: return "斜体";
                case XtraRichEditStringId.MenuCmd_MoveLineUpDescription: return "往上移一行";
                case XtraRichEditStringId.MenuCmd_ReplaceForwardDescription: return "向下取代";
                case XtraRichEditStringId.MenuCmd_DeleteDescription: return "删除";
                case XtraRichEditStringId.DefaultStyleName_heading8: return "标题 8";
                case XtraRichEditStringId.DefaultStyleName_footer: return "表尾";
                case XtraRichEditStringId.MenuCmd_ShowParagraphFormDescription: return "显示段落对话框.";
                case XtraRichEditStringId.DefaultStyleName_ListContinue: return "接续 ";
                case XtraRichEditStringId.DefaultStyleName_BodyTextIndent3: return "本文缩排 3";
                case XtraRichEditStringId.Msg_TableIntegrityError: return "错误: 表格不完整";
                case XtraRichEditStringId.MenuCmd_NewEmptyDocumentDescription: return "建立一份新文件.";
                case XtraRichEditStringId.MenuCmd_InsertTab: return "Insert键";
                case XtraRichEditStringId.MenuCmd_ParagraphAlignmentRight: return "靠右对齐";
                case XtraRichEditStringId.DefaultStyleName_TableColumns4: return "表格 栏4";
                case XtraRichEditStringId.FieldMapCity: return "城市";
                case XtraRichEditStringId.FieldMapAddress2: return "地址 2";
                case XtraRichEditStringId.DefaultStyleName_TableClassic2: return "表格 古典 2";
                case XtraRichEditStringId.Msg_UseDeletedFieldError: return "错误: 使用字段段落";
                case XtraRichEditStringId.FontStyle_Bold: return "粗体";
                case XtraRichEditStringId.MenuCmd_MovePreviousParagraphDescription: return "移到上一个段落";
                case XtraRichEditStringId.DefaultStyleName_ListBullet4: return "列表项目符号 4";
                case XtraRichEditStringId.UnitAbbreviation_Inch: return " 英吋";
                case XtraRichEditStringId.MenuCmd_ShowTabsForm: return "定位点";
                case XtraRichEditStringId.Msg_IncorrectNumericFieldFormat: return "错误: 数值字段无法套用指定的格式.";
                case XtraRichEditStringId.MenuCmd_DeleteWordCore: return "删除字符核心";
                case XtraRichEditStringId.MenuCmd_ShowAllFieldCodesDescription: return "显示所有字段代码";
                case XtraRichEditStringId.DefaultStyleName_BodyTextIndent2: return "本文缩排 2";
                case XtraRichEditStringId.DefaultStyleName_TableColumns3: return "表格 栏3";
                case XtraRichEditStringId.MenuCmd_ShowTabsFormDescription: return "定位点";
                case XtraRichEditStringId.MenuCmd_ChangeFontColorDescription: return "变更字型的颜色.";
                case XtraRichEditStringId.FieldMapUniqueId: return "单一标识符号";
                case XtraRichEditStringId.Caption_AlignmentRight: return "靠右对齐";
                case XtraRichEditStringId.DefaultStyleName_HTMLTopofForm: return "HTML Top of Form ";
                case XtraRichEditStringId.MenuCmd_QuickPrintDescription: return "不做其他的变更动作下直接将文件打印至默认打印机.";
                case XtraRichEditStringId.MenuCmd_ShowFontForm: return "字型";
                case XtraRichEditStringId.MenuCmd_ZoomIn: return "拉近";
                case XtraRichEditStringId.MenuCmd_MoveScreenDownDescription: return "往下移动一个屏幕显示的范围";
                case XtraRichEditStringId.MenuCmd_InsertNonBreakingSpaceDescription: return "插入接续本页符号";
                case XtraRichEditStringId.MenuCmd_ReplaceText: return "取代文字";

            }
            return base.GetLocalizedString(id);
        }
    }
}
